
filebeat.config.modules:

  path: /usr/share/filebeat/modules.d/*.yml
  reload.enabled: true
  #reload.period: 10s

filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]
- module: iptables
  log:
    enabled: true
    var.paths: ["/var/log/iptables.log"]
    var.input: "file"

- module: suricata
  eve:
    enabled: true
    var.paths: ["/var/log/suricata/fast.log","/var/log/suricata/suricata.log"]
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]
- module: logstash
  log:
    enabled: true
    var.paths: ["/var/log/logstash/logstash-plain.log*"]
    var.format: json
  slowlog:
    enabled: true
    var.paths: ["/var/log/logstash/logstash-slowlog.log*"]
    var.format: json

- module: elasticsearch
  server:
    enabled: true
    var.paths:
      - /var/log/elasticsearch/*.log
      - /var/log/elasticsearch/*_server.json
filebeat.inputs:
- type: docker
  enabled: true
  containers:
    stream: all # can be all, stdout or stderr
    ids:
      - '*'
#========================== Filebeat autodiscover ==============================
# See this URL on how to run Apache2 Filebeat module: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
#       # This URL alos contains instructions on multi-line logs
#       hints.enabled: true
setup.ilm.enabled: false 
ilm.enabled: false 
setup.template.overwrite: true




processors:
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true
#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

# #============================== Kibana =========================================
setup.kibana:
  host: "kibana:5601"

# #============================== elasticsearch ========================================= 
# output.elasticsearch:
#   hosts: ["192.168.2.76:9200"]

#============================== logstash =========================================
output.logstash:
      hosts: ["logstash:5044"]