version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    networks:
      - wordpress-network


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - "./wordpress/wp-content:/var/www/html/wp-content"
      - "./wordpress/wp-admin:/var/www/html/wp-admin"
      - "./wordpress/wp-includes:/var/www/html/wp-includes"
    ports:
      - "80:80"
    restart: always
    env_file: .env
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: $MYSQL_USER
        WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
        WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
    networks:
      - wordpress-network

volumes:
  wordpress:
  db_data:
networks:
  wordpress-network:
    driver: bridge 

