version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: wordpress
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html   
    ports:
      - "9000:9000" 
    env_file: .env
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: $MYSQL_USER
        WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
        WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
    networks:
      - wordpress-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    networks:
      - wordpress-network
 

volumes:
  wordpress:
  db_data:
  certbot-etc:
networks:
  wordpress-network:
    driver: bridge 

