version: '3.7'
services:
  elasticsearch:
    container_name: elastic
    restart: always
    build: ./SIEM+IDS+IPS/elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data 
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - tfm
    healthcheck:
      test: ["CMD", "curl","-s" , "http://localhost:9200/_cat/health"]
  logstash:
    container_name: logstash
    restart: always
    build: ./SIEM+IDS+IPS/logstash
    volumes: 
      - ./SIEM+IDS+IPS/suricata/var/log/suricata:/var/log/suricata:rw
      - ./SIEM+IDS+IPS/logstash/dist/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - tfm
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    networks:
      - tfm
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.7.0
    # command: --strict.perms=false
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      # - ${PWD}/configs/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - tfm
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    command: --strict.perms=false
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - 9000:9000
    volumes:
      # - ${PWD}/configs/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tfm
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: always
    command:
      - '-i eth0'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    network_mode: "host"
    volumes:
      - ./SIEM+IDS+IPS/suricata/etc/suricata.yaml:/etc/suricata/suricata.yaml
      - ./SIEM+IDS+IPS/suricata/etc/classification.config:/etc/suricata/classification.config
      - ./SIEM+IDS+IPS/suricata/etc/reference.config:/etc/suricata/reference.config
      - ./SIEM+IDS+IPS/suricata/rules/emerging-dos.rules:/var/lib/suricata/rules/emerging-dos.rules
      - ./SIEM+IDS+IPS/suricata/rules/ddos.rules:/var/lib/suricata/rules/ddos.rules
      - ./SIEM+IDS+IPS/suricata/rules/test-ddos.rules:/var/lib/suricata/rules/test-ddos.rules
      - ./SIEM+IDS+IPS/suricata/configs/disable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/disable.conf
      - ./SIEM+IDS+IPS/suricata/configs/drop.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/drop.conf
      - ./SIEM+IDS+IPS/suricata/configs/enable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/enable.conf
      - ./SIEM+IDS+IPS/suricata/configs/modify.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/modify.conf
      - ./SIEM+IDS+IPS/suricata/configs/update.yaml:/usr/lib/python3.7/site-packages/suricata/update/configs/update.yaml
      - ./SIEM+IDS+IPS/suricata/var/log/suricata:/var/log/suricata
  auditbeat:
    image: docker.elastic.co/beats/auditbeat:7.7.0
    command: auditbeat -e -strict.perms=false
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    pid: "host"
    volumes:
    #   - ${PWD}/configs/auditbeat.docker.yml:/usr/share/auditbeat/auditbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tfm
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.7.0
    command: --strict.perms=false
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    # volumes:
    #   - ${PWD}/configs/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml
    networks:
      - tfm
  nginx:
    container_name: load_balancer_monitoring
    image: nginx:alpine
    ports:
        - 8081:80
    networks:
        tfm:
            ipv4_address: 192.168.2.76
    volumes:
      - ./SIEM+IDS+IPS/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./SIEM+IDS+IPS/nginx/auth/basic.auth:/etc/nginx/basic.auth
volumes:
  elasticsearch:
  logs:

networks:
    tfm:
        ipam:
            driver: default
            config:
                - subnet: 192.168.2.0/24