version: '3.7'
services:
  wordpress:
    image: wordpress:5.4.0-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    networks:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    env_file: .env
    networks:
      - wordpress
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
  nginx:
    image: nginx
    restart: always
    networks:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress-data:/var/www/html
      - nginx-data:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - wordpress


      
volumes:
  wordpress-data:
  database-data:
  nginx-data:


networks:
  wordpress:
    driver: bridge
    name: wordpress