version: '3.7'
services:
  elasticsearch:
    container_name: elastic
    build: ./SIEM+IDS+IPS/elastic
    networks:
      siem_ids:
        ipv4_address: 192.168.56.101
  logstash:
    container_name: logstash
    build: ./SIEM+IDS+IPS/logstash
    networks:
      siem_ids:
        ipv4_address: 192.168.56.102
    volumes: 
      - ./var/log/suricata:/var/log/suricata:rw
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    networks:
      siem_ids:
        ipv4_address: 192.168.56.104
    ports:
      - "5601:5601"
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    command:
      - '-i eth0'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    network_mode: "host"
    volumes:
      - ./SIEM+IDS+IPS/suricata/etc/suricata.yaml:/etc/suricata/suricata.yaml
      - ./SIEM+IDS+IPS/suricata/etc/classification.config:/etc/suricata/classification.config
      - ./SIEM+IDS+IPS/suricata/etc/reference.config:/etc/suricata/reference.config
      - ./SIEM+IDS+IPS/suricata/rules/local.rules:/etc/suricata/rules/local.rules
      - ./SIEM+IDS+IPS/suricata/configs/disable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/disable.conf
      - ./SIEM+IDS+IPS/suricata/configs/drop.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/drop.conf
      - ./SIEM+IDS+IPS/suricata/configs/enable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/enable.conf
      - ./SIEM+IDS+IPS/suricata/configs/modify.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/modify.conf
      - ./SIEM+IDS+IPS/suricata/configs/update.yaml:/usr/lib/python3.7/site-packages/suricata/update/configs/update.yaml
      - ./SIEM+IDS+IPS/var/log/suricata:/var/log/suricata
      
networks:
  siem_ids:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 192.168.56.0/24 