version: '3.7'
services:
  elasticsearch:
    container_name: elastic
    build: elastic
    networks:
      wordpress:
        ipv4_address: 192.168.56.101
  logstash:
    container_name: logstash
    build: logstash
    networks:
      wordpress:
        ipv4_address: 192.168.56.102
    volumes: 
      - ./var/log/suricata:/var/log/suricata:rw
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    networks:
      wordpress:
        ipv4_address: 192.168.56.104
    ports:
      - "5601:5601"
  wordpress:
    image: wordpress:5.4.0-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    networks:
      wordpress:
        ipv4_address: 192.168.56.103
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    env_file: .env
    networks:
      wordpress:
        ipv4_address: 192.168.56.109
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    command:
      - '-i br-9f57429ba6d7'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    network_mode: "host"
    volumes:
      - ./suricata/etc/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/etc/classification.config:/etc/suricata/classification.config
      - ./suricata/etc/reference.config:/etc/suricata/reference.config
      - ./suricata/rules/local.rules:/etc/suricata/rules/local.rules
      - ./suricata/configs/disable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/disable.conf
      - ./suricata/configs/drop.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/drop.conf
      - ./suricata/configs/enable.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/enable.conf
      - ./suricata/configs/modify.conf:/usr/lib/python3.7/site-packages/suricata/update/configs/modify.conf
      - ./suricata/configs/update.yaml:/usr/lib/python3.7/site-packages/suricata/update/configs/update.yaml
      - ./var/log/suricata:/var/log/suricata
  nginx:
    build: ./openresty
    container_name: webserver
    restart: always
    networks:
      wordpress:
        ipv4_address: 192.168.56.106
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_main.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/anti_ddos_challenge.lua:/usr/local/openresty/nginx/anti_ddos_challenge.lua
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress-data:/var/www/html
      - nginx-data:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - wordpress


      
volumes:
  wordpress-data:
  database-data:
  nginx-data:


networks:
  wordpress:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 192.168.56.0/24 